import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import {
  Network,
  GitBranch,
  Boxes,
  Loader2,
  ChevronDown,
  ChevronUp,
} from "lucide-react";
import ReactMarkdown from "react-markdown";
import useRepoStore from "../store/repoStore";
function ArchSection({
  title,
  icon: Icon,
  content,
  color = "var(--accent-primary)",
}) {
  const [expanded, setExpanded] = useState(true);

  if (!content) return null;

  return (
    <div
      className="glass-card"
      style={{
        marginBottom: 20,
        overflow: "hidden",
      }}
    >
      <div
        onClick={() => setExpanded(!expanded)}
        style={{
          cursor: "pointer",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          padding: "18px 22px",
          borderBottom: expanded
            ? "1px solid var(--border)"
            : "none",
        }}
      >
        <div
          style={{
            display: "flex",
            gap: 12,
            alignItems: "center",
          }}
        >
          <div
            style={{
              width: 34,
              height: 34,
              borderRadius: 8,
              background: `${color}20`,
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            <Icon
              size={16}
              style={{
                color,
              }}
            />
          </div>

          <strong>{title}</strong>
        </div>

        {expanded ? (
          <ChevronUp size={18} />
        ) : (
          <ChevronDown size={18} />
        )}
      </div>

      {expanded && (
        <div
          style={{
            padding: 20,
          }}
        >
          <ReactMarkdown>
            {content}
          </ReactMarkdown>
        </div>
      )}
    </div>
  );
}
export default function Architecture() {
  const { repoId } = useParams();

  const {
    loadArchitecture,
    loadRepo,
    activeRepo,
    architecture,
    loading,
  } = useRepoStore();

  useEffect(() => {
    if (!repoId) return;

    if (!activeRepo) {
      loadRepo(repoId);
    }

    loadArchitecture(repoId);

  }, [repoId]);

  if (loading.architecture) {
    return (
      <div
        style={{
          height: "100vh",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <div style={{ textAlign: "center" }}>
          <Loader2
            size={36}
            className="animate-spin"
            style={{
              color: "var(--accent-primary)",
              marginBottom: 15,
            }}
          />

          <p>Loading Architecture...</p>
        </div>
      </div>
    );
  }

  if (!architecture) {
    return (
      <div
        style={{
          height: "100vh",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <div style={{ textAlign: "center" }}>
          <Network
            size={55}
            style={{
              opacity: .4,
              marginBottom: 15,
            }}
          />

          <h2>No Architecture Found</h2>

          <p>
            Repository analysis has not completed yet.
          </p>
        </div>
      </div>
    );
  }

  const overview = architecture.overview || "";

  const diagrams = architecture.diagrams || {};

  const sections = parseOverviewSections(overview);

  return (
    <div
      className="animate-fade-in"
      style={{
        padding: 35,
        maxWidth: 1200,
        margin: "0 auto",
      }}
    >

      <div
        style={{
          marginBottom: 35,
        }}
      >
        <h1
          style={{
            fontSize: 28,
            fontWeight: 700,
          }}
        >
          Repository Architecture
        </h1>

        <p
          style={{
            color: "var(--text-secondary)",
            marginTop: 8,
          }}
        >
          Complete architectural analysis generated by RepoMind AI.
        </p>
      </div>

      {sections.highLevel && (
        <ArchSection
          title="Architecture Overview"
          icon={Boxes}
          content={sections.highLevel}
          color="#6366F1"
        />
      )}

      {sections.dataFlow && (
        <ArchSection
          title="Data Flow"
          icon={GitBranch}
          content={sections.dataFlow}
          color="#06B6D4"
        />
      )}

      {sections.request && (
        <ArchSection
          title="Request Flow"
          icon={Network}
          content={sections.request}
          color="#A855F7"
        />
      )}

      {sections.modules && (
        <ArchSection
          title="Module Interaction"
          icon={Boxes}
          content={sections.modules}
          color="#22C55E"
        />
      )}

      {!sections.highLevel && overview && (
        <ArchSection
          title="Architecture"
          icon={Network}
          content={overview}
        />
      )}

      <div
        style={{
          marginTop: 40,
        }}
      >
        <h2
          style={{
            marginBottom: 20,
            fontWeight: 700,
          }}
        >
          Generated Architecture
        </h2>

        {Object.entries(diagrams).map(([title, value]) => (
          <div
            key={title}
            className="glass-card"
            style={{
              padding: 20,
              marginBottom: 25,
            }}
          >
            <h3
              style={{
                marginBottom: 15,
                textTransform: "capitalize",
              }}
            >
              {title.replace(/_/g, " ")}
            </h3>

            <pre
              style={{
                whiteSpace: "pre-wrap",
                fontFamily: "monospace",
                fontSize: 13,
                lineHeight: 1.6,
                overflowX: "auto",
              }}
            >
              {String(value)}
            </pre>
          </div>
        ))}
      </div>

    </div>
  );
}
function parseOverviewSections(text) {
  if (!text) {
    return {};
  }

  const sections = {};

  const lines = text.split("\n");

  let current = "highLevel";

  sections.highLevel = "";

  for (const line of lines) {
    const lower = line.toLowerCase();

    if (lower.includes("data flow")) {
      current = "dataFlow";
      sections.dataFlow = "";
      continue;
    }

    if (lower.includes("request flow")) {
      current = "request";
      sections.request = "";
      continue;
    }

    if (
      lower.includes("module interaction") ||
      lower.includes("modules")
    ) {
      current = "modules";
      sections.modules = "";
      continue;
    }

    if (
      lower.includes("overview") ||
      lower.includes("high level architecture")
    ) {
      current = "highLevel";
      continue;
    }

    if (!sections[current]) {
      sections[current] = "";
    }

    sections[current] += line + "\n";
  }

  Object.keys(sections).forEach((key) => {
    sections[key] = sections[key].trim();

    if (!sections[key]) {
      delete sections[key];
    }
  });

  return sections;
}