"""
Documentation generator: creates structured Markdown documentation
from repository analysis data — without requiring Ollama.
"""
from pathlib import Path
from typing import Any, Optional

from app.utils.file_utils import read_file_safe, _long_path
from app.utils.logger import get_logger

logger = get_logger(__name__)


def generate_all_docs(
    repo_path: Path,
    repo_meta: dict,
    tree_data: dict,
    tech_data: dict,
    file_analyses: dict,
    quality_data: dict,
    security_data: dict,
) -> dict:
    """Generate all documentation sections and return as a dict."""
    return {
        "readme": _generate_readme(repo_meta, tech_data, file_analyses),
        "architecture": _generate_architecture_doc(tree_data, tech_data, file_analyses),
        "api": _generate_api_doc(file_analyses, tech_data),
        "onboarding": _generate_onboarding(repo_meta, tech_data, tree_data, file_analyses),
        "installation": _generate_installation(repo_meta, tech_data),
        "learning_path": _generate_learning_path(repo_path, tech_data, tree_data, file_analyses),
        "folder_guide": _generate_folder_guide(tree_data),
    }


def _generate_readme(repo_meta: dict, tech_data: dict, file_analyses: dict) -> str:
    """Generate a comprehensive README."""
    name = repo_meta.get("name", "Project")
    owner = repo_meta.get("owner", "")
    desc = repo_meta.get("description", "A software project.")
    primary_lang = tech_data.get("primary_language", "Unknown")
    frameworks = [f["name"] for f in tech_data.get("frameworks", [])]

    # Find entry points
    entry_points = [
        path for path, a in file_analyses.items()
        if a and "entry point" in (a.get("purpose") or "").lower()
    ][:3]

    lines = [
        f"# {name}",
        "",
        f"> {desc}",
        "",
        "## 🛠️ Tech Stack",
        "",
        f"- **Primary Language**: {primary_lang}",
    ]

    if frameworks:
        lines.append(f"- **Frameworks**: {', '.join(frameworks)}")

    langs = tech_data.get("languages", [])
    if langs:
        lang_str = ", ".join(f"{l['name']} ({l['files']} files)" for l in langs[:5])
        lines.append(f"- **Languages**: {lang_str}")

    lines += [
        "",
        "## 🚀 Quick Start",
        "",
        "```bash",
        f"git clone https://github.com/{owner}/{name}.git",
        f"cd {name}",
        "```",
        "",
    ]

    if "Python" in primary_lang:
        lines += [
            "```bash",
            "python -m venv venv",
            "source venv/bin/activate  # Windows: venv\\Scripts\\activate",
            "pip install -r requirements.txt",
            "```",
        ]
    elif "JavaScript" in primary_lang or "TypeScript" in primary_lang:
        lines += [
            "```bash",
            "npm install",
            "npm run dev",
            "```",
        ]

    if entry_points:
        lines += [
            "",
            "## 📂 Entry Points",
            "",
        ]
        for ep in entry_points:
            lines.append(f"- `{ep}`")

    lines += [
        "",
        "## 📁 Project Structure",
        "",
        "See the [Architecture Documentation](architecture.md) for detailed structure.",
        "",
        "---",
        f"*Generated by RepoMind AI*",
    ]

    return "\n".join(lines)


def _generate_architecture_doc(tree_data: dict, tech_data: dict, file_analyses: dict) -> str:
    """Generate an architecture overview document."""
    stats = tree_data.get("stats", {})
    primary_lang = tech_data.get("primary_language", "Unknown")
    frameworks = [f["name"] for f in tech_data.get("frameworks", [])]

    lines = [
        "# Architecture Overview",
        "",
        "## System Summary",
        "",
        f"- **Primary Language**: {primary_lang}",
        f"- **Total Files**: {stats.get('total_files', 0)}",
        f"- **Total Directories**: {stats.get('total_dirs', 0)}",
        f"- **Codebase Size**: {stats.get('total_size_mb', 0):.1f} MB",
        "",
    ]

    if frameworks:
        lines += ["## Technology Layer", ""]
        # Group by category
        categories = tech_data.get("categories", {})
        for cat, techs in categories.items():
            lines.append(f"**{cat}**: {', '.join(techs)}")
        lines.append("")

    # Top-level directory structure
    root = tree_data.get("root", {})
    dirs = [c for c in root.get("children", []) if c.get("type") == "directory"]

    if dirs:
        lines += ["## Directory Structure", ""]
        for d in dirs[:15]:
            purpose = d.get("purpose", "")
            count = d.get("child_count", 0)
            purpose_str = f" — {purpose}" if purpose else ""
            lines.append(f"- **`{d['name']}/`** ({count} items){purpose_str}")

    lines += [
        "",
        "## Key Files",
        "",
    ]

    # Entry points and configs
    important = []
    for path, analysis in list(file_analyses.items())[:100]:
        if not analysis:
            continue
        purpose = analysis.get("purpose", "")
        if any(kw in purpose.lower() for kw in ["entry point", "configuration", "main"]):
            important.append((path, purpose))

    for path, purpose in important[:10]:
        lines.append(f"- **`{path}`**: {purpose}")

    lines += [
        "",
        "---",
        "*Generated by RepoMind AI*",
    ]
    return "\n".join(lines)


def _generate_api_doc(file_analyses: dict, tech_data: dict) -> str:
    """Generate API endpoint documentation from analysis."""
    lines = [
        "# API Documentation",
        "",
        "Auto-generated from repository analysis.",
        "",
    ]

    # Find API-related files
    api_files = [
        (path, analysis)
        for path, analysis in file_analyses.items()
        if analysis and "api" in path.lower() or "route" in path.lower() or "endpoint" in path.lower()
    ]

    if not api_files:
        lines.append("No API files detected automatically. Analyze route files manually.")
        return "\n".join(lines)

    for path, analysis in api_files[:20]:
        if not analysis:
            continue
        lines += [f"## `{path}`", ""]
        purpose = analysis.get("purpose", "")
        if purpose:
            lines.append(f"**Purpose**: {purpose}")
            lines.append("")

        functions = analysis.get("functions", [])
        if functions:
            lines.append("**Endpoints/Functions**:")
            for func in functions[:10]:
                name = func.get("name", str(func)) if isinstance(func, dict) else str(func)
                args = func.get("args", []) if isinstance(func, dict) else []
                args_str = f"({', '.join(args)})" if args else "()"
                lines.append(f"- `{name}{args_str}`")
        lines.append("")

    lines += ["---", "*Generated by RepoMind AI*"]
    return "\n".join(lines)


def _generate_onboarding(
    repo_meta: dict, tech_data: dict, tree_data: dict, file_analyses: dict
) -> str:
    """Generate a developer onboarding guide."""
    name = repo_meta.get("name", "this project")
    primary_lang = tech_data.get("primary_language", "Unknown")
    frameworks = [f["name"] for f in tech_data.get("frameworks", [])]

    lines = [
        f"# Developer Onboarding Guide — {name}",
        "",
        "Welcome! This guide will help you get up to speed with the codebase.",
        "",
        "## Step 1: Understand the Project",
        "",
        f"This is a **{primary_lang}** project",
    ]

    if frameworks:
        lines[-1] += f" using **{', '.join(frameworks[:3])}**."
    else:
        lines[-1] += "."

    desc = repo_meta.get("description", "")
    if desc:
        lines += ["", desc]

    lines += [
        "",
        "## Step 2: Set Up Your Environment",
        "",
    ]

    if "Python" in primary_lang:
        lines += [
            "```bash",
            "python -m venv venv",
            "source venv/bin/activate",
            "pip install -r requirements.txt",
            "```",
        ]
    elif primary_lang in {"JavaScript", "TypeScript"}:
        lines += [
            "```bash",
            "npm install",
            "```",
        ]

    lines += [
        "",
        "## Step 3: Explore the Codebase",
        "",
        "Start with these key directories:",
        "",
    ]

    # Show top-level dirs with purposes
    root = tree_data.get("root", {})
    dirs = [c for c in root.get("children", []) if c.get("type") == "directory"]
    for d in dirs[:8]:
        purpose = d.get("purpose", f"Contains {d['name']}-related code")
        lines.append(f"- **`{d['name']}/`**: {purpose}")

    lines += [
        "",
        "## Step 4: Find the Entry Point",
        "",
    ]

    entries = [
        p for p, a in file_analyses.items()
        if a and "entry point" in (a.get("purpose") or "").lower()
    ][:3]

    if entries:
        for e in entries:
            lines.append(f"- `{e}`")
    else:
        lines.append("- Look for `main.py`, `app.py`, `server.js`, or `index.js`")

    lines += [
        "",
        "## Step 5: Run the Project",
        "",
    ]

    if "Django" in frameworks:
        lines += ["```bash", "python manage.py runserver", "```"]
    elif "FastAPI" in frameworks:
        lines += ["```bash", "uvicorn app.main:app --reload", "```"]
    elif "Flask" in frameworks:
        lines += ["```bash", "flask run", "```"]
    elif "Next.js" in frameworks or "React" in frameworks:
        lines += ["```bash", "npm run dev", "```"]
    elif "Express.js" in frameworks:
        lines += ["```bash", "node server.js", "# or", "npm start", "```"]
    else:
        lines += ["```bash", "# Check README for run instructions", "```"]

    lines += [
        "",
        "---",
        "*Generated by RepoMind AI*",
    ]
    return "\n".join(lines)


def _generate_installation(repo_meta: dict, tech_data: dict) -> str:
    """Generate an installation guide."""
    name = repo_meta.get("name", "Project")
    owner = repo_meta.get("owner", "")
    primary_lang = tech_data.get("primary_language", "Unknown")
    frameworks = [f["name"] for f in tech_data.get("frameworks", [])]

    lines = [
        f"# Installation Guide — {name}",
        "",
        "## Prerequisites",
        "",
    ]

    if "Python" in primary_lang:
        lines += ["- Python 3.8 or higher", "- pip package manager"]
    if "JavaScript" in primary_lang or "TypeScript" in primary_lang:
        lines += ["- Node.js 16 or higher", "- npm or yarn"]
    if "Java" in primary_lang:
        lines += ["- Java 11 or higher", "- Maven or Gradle"]
    if "Go" in primary_lang:
        lines += ["- Go 1.19 or higher"]

    if "Docker" in frameworks or "Docker Compose" in frameworks:
        lines += ["- Docker (optional, for containerized setup)"]

    lines += [
        "",
        "## Clone the Repository",
        "",
        "```bash",
        f"git clone https://github.com/{owner}/{name}.git",
        f"cd {name}",
        "```",
        "",
        "## Install Dependencies",
        "",
    ]

    if "Python" in primary_lang:
        lines += [
            "```bash",
            "python -m venv venv",
            "source venv/bin/activate  # Windows: .\\venv\\Scripts\\activate",
            "pip install -r requirements.txt",
            "```",
        ]
    if "JavaScript" in primary_lang or "TypeScript" in primary_lang:
        lines += [
            "```bash",
            "npm install",
            "# or",
            "yarn install",
            "```",
        ]

    if "Docker Compose" in frameworks:
        lines += [
            "",
            "## Docker Setup (Alternative)",
            "",
            "```bash",
            "docker-compose up -d",
            "```",
        ]

    lines += [
        "",
        "## Environment Variables",
        "",
        "Copy the example environment file and fill in your values:",
        "",
        "```bash",
        "cp .env.example .env",
        "# Edit .env with your configuration",
        "```",
        "",
        "---",
        "*Generated by RepoMind AI*",
    ]
    return "\n".join(lines)


def _generate_learning_path(
    repo_path: Path, tech_data: dict, tree_data: dict, file_analyses: dict
) -> list[dict]:
    """Generate a step-by-step learning path for understanding the codebase."""
    steps = []

    # Step 1: README
    for name in ["README.md", "README.txt", "readme.md"]:
        if Path(_long_path(repo_path / name)).exists():
            steps.append({
                "step": 1,
                "title": "Read the README",
                "description": "Start with the project overview, installation, and usage instructions.",
                "file": name,
                "icon": "📖",
            })
            break
    if not steps:
        steps.append({
            "step": 1,
            "title": "Read the README",
            "description": "No README found — look for documentation in the /docs folder.",
            "file": None,
            "icon": "📖",
        })

    # Step 2: Configuration
    config_files = []
    for path in file_analyses:
        analysis = file_analyses[path]
        if analysis and "configuration" in (analysis.get("purpose") or "").lower():
            config_files.append(path)
    steps.append({
        "step": 2,
        "title": "Understand the Configuration",
        "description": "Review environment variables and configuration files.",
        "file": config_files[0] if config_files else ".env.example",
        "icon": "⚙️",
    })

    # Step 3: Entry point
    entries = [
        p for p, a in file_analyses.items()
        if a and "entry point" in (a.get("purpose") or "").lower()
    ]
    steps.append({
        "step": 3,
        "title": "Find the Entry Point",
        "description": "This is where the application starts. Trace execution from here.",
        "file": entries[0] if entries else None,
        "icon": "🚀",
    })

    # Step 4: Models/Schemas
    models = [p for p in file_analyses if "model" in p.lower() or "schema" in p.lower()]
    steps.append({
        "step": 4,
        "title": "Study Data Models",
        "description": "Understand the data structures the application works with.",
        "file": models[0] if models else None,
        "icon": "🗄️",
    })

    # Step 5: API/Routes
    apis = [p for p in file_analyses if "api" in p.lower() or "route" in p.lower()]
    steps.append({
        "step": 5,
        "title": "Explore APIs & Routes",
        "description": "Learn what endpoints or routes the application exposes.",
        "file": apis[0] if apis else None,
        "icon": "🔌",
    })

    # Step 6: Frontend/Views
    frontend = [p for p in file_analyses if p.endswith((".jsx", ".tsx", ".vue", ".html"))]
    if frontend:
        steps.append({
            "step": 6,
            "title": "Study the Frontend",
            "description": "Understand the user interface components and pages.",
            "file": frontend[0],
            "icon": "🎨",
        })

    # Step 7: Tests
    tests = [p for p in file_analyses if "test" in p.lower() or "spec" in p.lower()]
    steps.append({
        "step": len(steps) + 1,
        "title": "Run the Tests",
        "description": "Execute the test suite to verify everything works correctly.",
        "file": tests[0] if tests else None,
        "icon": "🧪",
    })

    return steps


def _generate_folder_guide(tree_data: dict) -> list[dict]:
    """Generate a folder-by-folder guide from the tree data."""
    folders = []

    def _collect_folders(node: dict, depth: int = 0):
        if node.get("type") == "directory" and depth <= 2:
            purpose = node.get("purpose", "")
            if node.get("name") and node["name"] not in {".", ""}:
                files = [c for c in node.get("children", []) if c.get("type") == "file"]
                subdirs = [c for c in node.get("children", []) if c.get("type") == "directory"]
                folders.append({
                    "name": node["name"],
                    "path": node["path"],
                    "purpose": purpose or f"Contains {node['name']}-related files",
                    "file_count": len(files),
                    "subdir_count": len(subdirs),
                    "depth": depth,
                })
            for child in node.get("children", []):
                _collect_folders(child, depth + 1)

    _collect_folders(tree_data.get("root", {}))
    return folders
